### PR TITLE
#3 - Preserve Markdown trailing whitespace

### PR DESCRIPTION
**Pull request by AramZS**
I was not aware that line-breaks were created with a double space at the end of a line. Very cool! Updated rules to preserve this technique. 

Figured I'd also get ahead of potential YAML use and add rules to preserve its requirements as well. 

Should resolve most of #3

### CODE REVIEW

**Comment by peterkaminski** [comment]
@AramZS, I think the `[*.{yaml,yml}]` section won't work for our YAML, because YAML frontmatter is embedded in `.md` files.

(I'm guessing `[*.{yaml,yml}]` means "files with YAML extensions, right?)

WDYT?

**Comment by AramZS** [comment]
@peterkaminski It depends on what editor the user is using! I have an additional configuration at the editor level that handles it, but not all users might. I'm fine switching it over to 2 spaces / tab (though that is not my personal preference), but we should be prepared to have some big changesets every time someone touches an older file, at least for a while until the editors' autofix smooth out all the changes.

**Comment by AramZS** [comment]
As per the discussion, this is now two spaces === tab in markdown in order to support wide editor use and configuration using editorconfig.

**Comment by AramZS** [comment]
See for most notable reference: 

https://github.com/editorconfig/specification/pull/38
https://github.com/editorconfig/editorconfig/issues/323

**Review by peterkaminski — APPROVED** [review]
lgtm, thanks for the consideration and research, Aram!

**Pull request merged**
